name: management_states
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  go_router:
  lottie:
  auto_size_text:
  flutter_svg: ^2.0.9
  flutter_bloc:
  google_maps_flutter: ^2.5.3
  mapbox_gl:
  http:
  geolocator: ^11.0.0
  flutter_localization:
  motion_toast: ^2.9.0
  fluttertoast: ^8.0.9
  flutter_map: ^6.1.0
  latlong2:
  google_fonts: 6.0.0
  rxdart: ^0.27.2
  freezed:
  freezed_annotation:
  json_serializable:
  shared_preferences: ^2.2.2
  intl_utils: ^2.8.2
  dio:
  supabase_flutter: ^2.5.8
  flutter_speed_dial: ^7.0.0
  optimize_battery: ^0.0.4
  flutter_local_notifications: ^7.0.0
  firebase_core:
  firebase_messaging:
  get_it: ^7.6.4
  cached_network_image: ^3.2.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  freezed:
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

  assets:
   - assets/images/
   - assets/icons/
   - assets/fonts/

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Light.ttf
          weight: 100
        - asset: assets/fonts/Cairo-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Cairo-Regular.ttf
          weight: 300
        - asset: assets/fonts/Cairo-Medium.ttf
          weight: 400
        - asset: assets/fonts/Cairo-SemiBold.ttf
          weight: 500
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 600
        - asset: assets/fonts/Cairo-ExtraBold.ttf
          weight: 700
        - asset: assets/fonts/Cairo-Black.ttf
          weight: 800


flutter_intl:
   enabled: true
   class_name: S
   main_locale: ar_SY
   arb_dir: lib/localization/l10n
   output_dir: lib/localization/generated